import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f8f9ff' },
  scrollView: { padding: 15 },
  header: {
    fontSize: 22,
    fontWeight: 'bold',
    marginBottom: 15,
    textAlign: 'center',
  },
  card: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 15,
    marginBottom: 10,
    elevation: 3,
  },
  cardTitle: { fontSize: 18, fontWeight: 'bold', marginBottom: 5 },
  cardText: { fontSize: 15, color: '#555' },
  buttonRow: { flexDirection: 'row', marginTop: 10, justifyContent: 'space-between' },
  btnEdit: {
    backgroundColor: '#5a67d8',
    padding: 10,
    borderRadius: 8,
    flex: 1,
    marginRight: 5,
  },
  btnEditText: { color: '#fff', textAlign: 'center' },
  btnDelete: {
    backgroundColor: '#e53e3e',
    padding: 10,
    borderRadius: 8,
    flex: 1,
    marginLeft: 5,
  },
  btnDeleteText: { color: '#fff', textAlign: 'center' },
  fabButton: {
    position: 'absolute',
    bottom: 25,
    right: 25,
    backgroundColor: '#667eea',
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  fabText: { fontSize: 30, color: '#fff', fontWeight: 'bold', marginTop: -3 },
  modalContainer: { flex: 1, padding: 20 },
  modalTitle: { fontSize: 20, fontWeight: 'bold', marginBottom: 15 },
  input: {
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 10,
    padding: 10,
    marginBottom: 10,
  },
  btnPrimary: {
    backgroundColor: '#667eea',
    padding: 15,
    borderRadius: 10,
    marginTop: 10,
  },
  btnPrimaryText: { color: '#fff', fontWeight: 'bold', textAlign: 'center' },
  btnCancel: {
    backgroundColor: '#ccc',
    padding: 15,
    borderRadius: 10,
    marginTop: 10,
  },
  btnCancelText: { textAlign: 'center' },
});
